---
title: "age_distribution"
author: "Maisy Hallam"
date: "2023-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
library(readr)
```

Import the age data. It has three columns: language number (1-1000),
gender symmetry score, and set (which simulation it comes from.)

```{r}
lineage_sims <- list.files(path="data/lineage/new/",pattern="*.csv",full.names=TRUE)
data <- do.call(rbind, lapply(lineage_sims, function(x) read.csv(x)))
real_data <- read_csv('data/kinbank_lineage.csv')

```

```{r}
data$LINEAGE <- as.factor(data$LINEAGE)
```


```{r}
sym_proportion <- group_by(data,SET) %>%
  summarise(
    mean_symmetrical = mean(LINEAGE == '[1, 1]')
  )
```

```{r}
sym_proportion
```

```{r}
real_data <- real_data %>%
  mutate(
    SET = 'kinbank'
  )
```

```{r}
kinbank <- group_by(real_data,SET) %>%
  summarise(
    mean_symmetrical = mean(LINEAGE == '[1, 1]')
)
```

```{r}
all_data <- rbind(sym_proportion,kinbank)
```


```{r}
sym_proportion %>%
  ggplot(aes(mean_symmetrical)) +
  geom_density(fill = 'lightblue', alpha = 1) +
  geom_vline(aes(xintercept = 0.4250), color="navy", linetype="dashed", size=0.5) +
  labs(
    title = 'Distribution of 1,1 side of the family symmetry scores',
    color = legend) +
  xlab('Proportion of 1,1 symmetry') +
  xlim(0.1,0.45)
  
ggsave('plots/lineage_1,1_density.png')
```

```{r}
proportion_10 <- group_by(data,SET) %>%
  summarise(
    mean = mean(LINEAGE == '[1, 0]')
  )

proportion_01 <- group_by(data,SET) %>%
  summarise(
    mean = mean(LINEAGE == '[0, 1]')
  )

proportion_00 <- group_by(data,SET) %>%
  summarise(
    mean = mean(LINEAGE == '[0, 0]')
  )
```

```{r}
kinbank_prop_10 <- real_data %>%
  summarise(
    mean = mean(LINEAGE == '[1, 0]')
)

kinbank_prop_01 <- real_data %>%
  summarise(
    mean = mean(LINEAGE == '[0, 1]')
)

kinbank_prop_00 <- real_data %>%
  summarise(
    mean = mean(LINEAGE == '[0, 0]')
)

kinbank_prop_10
kinbank_prop_01
kinbank_prop_00
```

```{r}
proportion_10 %>%
  ggplot(aes(mean)) +
  geom_density(fill = 'lightblue', alpha = 1) +
  geom_vline(aes(xintercept = 0.0795), color="navy", linetype="dashed", size=0.5) +
  labs(
    title = 'Proportion of 1,0 side of the family asymmetry scores',
    color = legend) +
  xlab('Proportion of 1,0 asymmetry') +
  xlim(0,0.15)

ggsave('plots/lineage_1,0_density.png')
```

```{r}
proportion_01 %>%
  ggplot(aes(mean)) +
  geom_density(fill = 'lightblue', alpha = 1) +
  geom_vline(aes(xintercept = 0.2269), color="navy", linetype="dashed", size=0.5) +
  labs(
    title = 'Proportion of 0,1 side of the family asymmetry scores',
    color = legend) +
  xlab('Proportion of 0,1 asymmetry') +
  xlim(0.2,0.7)

ggsave('plots/lineage_0,1_density.png')
```

```{r}
proportion_00 %>%
  ggplot(aes(mean)) +
  geom_density(fill = 'lightblue', alpha = 1) +
  geom_vline(aes(xintercept = 0.2686), color="navy", linetype="dashed", size=0.5) +
  labs(
    title = 'Proportion of 0,0 side of the family asymmetry scores',
    color = legend) +
  xlab('Proportion of 0,0 symmetry') +
  xlim(0,0.3)

ggsave('plots/lineage_0,0_density.png')
```

