---
title: "lineage_proportion"
author: "Maisy Hallam"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
```

```{r import files}
lineage_prop_files <- list.files(path="data/lineage/prop/",pattern="*.csv",full.names=TRUE)
lineage_data <- do.call(rbind, lapply(lineage_prop_files, function(x) read.csv(x)))
```

```{r mutate data to include which dataset it's from}
lineage_data <- lineage_data %>%
  mutate(
    
    TYPE = ifelse (grepl('frankenlanguage', LANGUAGE),
    'simulation',
    'kinbank'
  ))
```

```{r remove extra headers (run twice)}
#lineage_data <- lineage_data[-1,]
```

```{r make data numeric}
lineage_data$GEN_0 <- as.numeric(lineage_data$GEN_0)

lineage_data$GEN_1 <- as.numeric(lineage_data$GEN_1)

```

```{r split the data by dataset}
simulation_proportions <- filter(lineage_data,TYPE == 'simulation')
kinbank_proportions <- filter(lineage_data,TYPE == 'kinbank')
```

```{r sample the data}
sim_prop_sample <- sample_n(simulation_proportions,767, replace=FALSE)
kinbank_prop_sample <- sample_n(kinbank_proportions,767,replace=FALSE)
```

```{r combine samples}
lineage_sampled <- rbind(sim_prop_sample,kinbank_prop_sample)
```


```{r plot the data}
lineage_sampled %>%
  ggplot(aes(TYPE,GEN_0,fill = TYPE)) +
  geom_violin() +
  geom_jitter(width = 0.1, alpha = 0.2) +
  labs(
    title = "Proportion of relationships that are distinguished by parent relation in Ego's generation",
    color = legend) +
  xlab('Proportion of relationships')

#ggsave('plots/lineage_proportion_jitter.png')
```

```{r}
lineage_sampled %>%
  ggplot(aes(GEN_0,fill = TYPE)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Distribution of relationships that are distinguished by parent relation in Ego's generation",
    color = legend) +
  xlab('Proportion of relationships') +
  xlim(0,1)

#ggsave('plots/lineage_g1_proportion_density.png')
```

```{r}
lineage_sampled %>%
  ggplot(aes(GEN_1,fill = TYPE)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Distribution of relationships that are distinguished by parent relation in Ego's Parents' generation",
    color = legend) +
  xlab('Proportion of relationships') +
  xlim(0,1)

#ggsave('plots/lineage__g2_proportion_density.png')
```

```{r}
lineage_sampled %>%
  ggplot() +
  geom_jitter(aes(x=GEN_0, y=GEN_1,color=TYPE),alpha=0.2,width=0.2) +
  xlim(0,1) +
  ylim(0,1)
```

```{r}
summary(lineage_sampled)
```

## Comparing Indo_European with Austronesian

```{r read language family data}
ie_l <- read_csv('data/lineage/prop/families/kinbank_Indo-European.csv')
an_l <- read_csv('data/lineage/prop/families/kinbank_Austronesian.csv')
```

```{r}
ie_l_sample <- sample_n(ie,95, replace=FALSE)
an_l_sample <- sample_n(am,95,replace=FALSE)
```


```{r}
iean_l <- rbind(ie_l_sample,an_l_sample)
```

```{r}
iean_l %>%
  ggplot(aes(GEN_0,fill = SET)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Distribution of relationships that are distinguished by parent relation in Ego's generation",
    color = legend) +
  xlab('Proportion of relationships') +
  xlim(0,1)
```

```{r}
iean_l %>%
  ggplot(aes(GEN_1,fill = SET)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Distribution of relationships that are distinguished by parent relation in Ego's parents' generation",
    color = legend) +
  xlab('Proportion of relationships') +
  xlim(0,1)
```

```{r}
iean_l %>%
  ggplot() +
  geom_jitter(aes(x=GEN_0, y=GEN_1,color=SET),alpha=0.2)
```